apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: e2e-tests-go-gxzmrmmh-import
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-go-gxzmrmmh-import 
  name: e2e-tests-go-gxzmrmmh-import
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: e2e-tests-go-gxzmrmmh-import 
